name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Docker イメージの tar アーカイブ出力先のパス
  PATH_CACHE: /tmp/docker-img-arch
  TAG: latex-container
  VARIANT: $(TZ=UTC-9 date '+%Y%m%d%H%M%S')

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリの読み込み（fetch-depth=1）
      - name: Check out repo under workspace
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        id: build-image
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ env.TAG }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: docker build
        run: make build
      - name: docker build check
        if: ${{failure()}}
        run: make rebuild

  BuildOnCache:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: Build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      # - name: Cache Docker layers
      #   uses: actions/cache@v3
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-
      - uses: docker/build-push-action@v2
        id: build-image
        with:
          context: ./
          file: ./Dockerfile
          push: false
          tags: ${{ env.TAG }}:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
