name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Docker イメージの tar アーカイブ出力先のパス
  TAG: latex-container
  USER_NAME: guest

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリの読み込み（fetch-depth=1）
      - name: Check out repo under workspace
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: test
        run: |
          echo "hogehoge" > test.txt
          ls -al
          cat test.txt

