name: build

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  # Docker イメージの tar アーカイブ出力先のパス
  TAG: latex-container
  TS: $(TZ=UTC-9 date '+%Y%m%d%H%M%S')
  USER_NAME: guest

jobs:
  Build:
    runs-on: ubuntu-22.04
    steps:
      # リポジトリの読み込み（fetch-depth=1）
      - name: Check out repo under workspace
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: use cache build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          build-args: TS=${{ env.TS }},DOCKER_USER_=${{ env.USER_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: docker build check
        if: ${{ failure() }}
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.TAG }}
          build-args: DOCKER_USER_=${{ env.USER_NAME }}
          cache-to: type=gha,mode=max
          pull: true
          no-cache: true
      - name: check
        run: |
          docker images
          docker ps
          make pre-exec_
          make post-exec_

  BuildOnCache:
    runs-on: ubuntu-22.04
    timeout-minutes: 30
    needs: Build
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: setup docker
        uses: docker/setup-buildx-action@v2
      - name: run
        run: |
          docker images
          docker ps
          make pre-exec_
          make post-exec_
